// ...existing code...
// This file is a proxy to the actual AddVehicleModal component in app/components/AddVehicleModal.js
import AddVehicleModal from '../app/components/AddVehicleModal';
export default AddVehicleModal;
// ...existing code...
