// ...existing code...
// This file is a proxy to the actual QuickEditModal component in app/components/QuickEditModal.js
import QuickEditModal from '../app/components/QuickEditModal';
export default QuickEditModal;
// ...existing code...
