// ...existing code...
// This file is a proxy to the actual VehicleManageModal component in app/components/VehicleManageModal.js
import VehicleManageModal from '../app/components/VehicleManageModal';
export default VehicleManageModal;
// ...existing code...
