# Generated by Django 4.2.21 on 2025-06-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_email_verification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='partner',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='partner_docs/'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['verification_status'], name='core_partne_verific_d03d23_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
    ]
