# Generated by Django 4.2.21 on 2025-06-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='verification_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
