# Generated by Django 4.2.21 on 2025-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_partner_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='partner_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
