--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO airbcar_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO airbcar_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO airbcar_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_booking; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.core_booking (
    id bigint NOT NULL,
    date date NOT NULL,
    listing_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.core_booking OWNER TO airbcar_user;

--
-- Name: core_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.core_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_listing; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.core_listing (
    id bigint NOT NULL,
    make character varying(50) NOT NULL,
    model character varying(50) NOT NULL,
    year integer NOT NULL,
    price_per_day numeric(10,2) NOT NULL,
    availability boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    partner_id bigint NOT NULL
);


ALTER TABLE public.core_listing OWNER TO airbcar_user;

--
-- Name: core_listing_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.core_listing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_listing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_partner; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.core_partner (
    id bigint NOT NULL,
    company_name character varying(100) NOT NULL,
    tax_id character varying(50) NOT NULL,
    verification_status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    verification_document character varying(100)
);


ALTER TABLE public.core_partner OWNER TO airbcar_user;

--
-- Name: core_partner_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.core_partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.core_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    phone_number character varying(15) NOT NULL,
    profile_picture character varying(100),
    default_currency character varying(3) NOT NULL,
    is_partner boolean NOT NULL,
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    email_verification_token character varying(36),
    email_verified boolean NOT NULL
);


ALTER TABLE public.core_user OWNER TO airbcar_user;

--
-- Name: core_user_groups; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.core_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.core_user_groups OWNER TO airbcar_user;

--
-- Name: core_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.core_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.core_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user_user_permissions; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.core_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.core_user_user_permissions OWNER TO airbcar_user;

--
-- Name: core_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.core_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO airbcar_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO airbcar_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO airbcar_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: airbcar_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: airbcar_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO airbcar_user;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add booking	6	add_booking
22	Can change booking	6	change_booking
23	Can delete booking	6	delete_booking
24	Can view booking	6	view_booking
25	Can add user	7	add_user
26	Can change user	7	change_user
27	Can delete user	7	delete_user
28	Can view user	7	view_user
29	Can add partner	8	add_partner
30	Can change partner	8	change_partner
31	Can delete partner	8	delete_partner
32	Can view partner	8	view_partner
33	Can add listing	9	add_listing
34	Can change listing	9	change_listing
35	Can delete listing	9	delete_listing
36	Can view listing	9	view_listing
\.


--
-- Data for Name: core_booking; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.core_booking (id, date, listing_id, user_id) FROM stdin;
1	2025-06-07	1	2
\.


--
-- Data for Name: core_listing; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.core_listing (id, make, model, year, price_per_day, availability, created_at, partner_id) FROM stdin;
1	Toyota	Camry	2020	50.00	t	2025-06-07 01:29:38.366545+01	1
2	Honda	Civic	2019	45.00	t	2025-06-07 01:29:38.372568+01	1
\.


--
-- Data for Name: core_partner; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.core_partner (id, company_name, tax_id, verification_status, created_at, user_id, verification_document) FROM stdin;
1	Partner1 Rentals	TAX123	approved	2025-06-07 01:29:38.347525+01	1	\N
6	Test Co	12345	pending	2025-06-17 08:25:58.288419+01	6	\N
\.


--
-- Data for Name: core_user; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.core_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone_number, profile_picture, default_currency, is_partner, is_verified, created_at, email_verification_token, email_verified) FROM stdin;
3	pbkdf2_sha256$600000$fD1apCULSWtmTAf3sky4G5$tuUph3XXe7F3cw12p0eq3jdJU3XFxZicZ0OTgNwkNVg=	2025-06-17 08:11:38.679169+01	t	amine			amine@example.com	t	t	2025-06-09 00:45:21.961389+01	+212		MAD	f	f	2025-06-09 00:45:22.089339+01	\N	f
5	pbkdf2_sha256$600000$u3uE0l08fLskoPE8O1A9Bs$OaMuv6ako3XlqSWepPj8NvssM9Gh/lAZrGvWW5EeQ0A=	\N	f	APTX-4869			aptx-4869@example.com	f	t	2025-06-09 01:37:47.440128+01	+1234567890		USD	f	f	2025-06-09 01:37:47.4404+01	5d8a3347-478b-4fda-8852-f16a94f7d341	f
1	pbkdf2_sha256$600000$bi5fhIOWK5PqJZkp11jhjB$1z5NpoQ55W7ZMu9IJ7Jy4fDuUnbH1BhbzwZrvSCu3+E=	\N	f	partner1			partner1@example.com	f	t	2025-06-07 01:28:44.019975+01			USD	t	f	2025-06-07 01:28:44.15388+01	\N	f
2	pbkdf2_sha256$600000$Gnh3e66MgYucb6ktdsorpM$pC4n7jty1BD5SzzRLRxa212vIY+JQ2rkWFJuaOD620E=	\N	f	renter1			renter1@example.com	f	t	2025-06-07 01:28:44.200532+01			USD	f	f	2025-06-07 01:28:44.328472+01	\N	f
8	pbkdf2_sha256$600000$qlv6qbiH8DMs5zAtmwo4uW$s66ngyQ/WIWpsBo2LX4mp9GZOPpp/G2ujgHZg9TcQI0=	\N	f	newuser			newuser@example.com	f	t	2025-06-17 20:03:42.303108+01			USD	f	f	2025-06-17 20:03:42.303357+01	62c106a0-0e6d-4d7d-b69c-d89a8af06672	f
10	pbkdf2_sha256$600000$fu3HTtAAATZQQlXgdGj5Oj$8irLksBFkh2woEQKLOIdK+3xebcwwJs/QzKbERaVcpE=	\N	f	ziyad			ziyad@example.com	f	t	2025-06-18 10:43:44+01			USD	f	t	2025-06-18 10:43:44.179887+01	\N	t
6	pbkdf2_sha256$600000$d2up4coLJn8Vqd9XnxtNxO$F0K5zbbTznEmquIJzvsdKQ5zov2jHpGLN1egbeKZrIs=	\N	f	JIN			JIN@example.com	f	t	2025-06-17 05:56:33+01	999		USD	f	f	2025-06-17 05:56:33.882266+01	abcd12	t
11	pbkdf2_sha256$600000$f33FY3TvhjjJvCkuRYXLn2$oP9fnVTQLS+Qe/Fh4JYTugHuih0YYzMmErzGI/J2g6U=	\N	f	yahya			yahya@example.com	f	t	2025-06-18 10:54:28+01			USD	f	t	2025-06-18 10:54:28.758513+01	\N	t
\.


--
-- Data for Name: core_user_groups; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.core_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: core_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.core_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-06-17 08:22:08.355287+01	2	Rental car (testuser2)	1	[{"added": {}}]	8	3
2	2025-06-17 08:46:40.841498+01	6	JIN	2	[{"changed": {"fields": ["Email verification token", "Email verified"]}}]	7	3
3	2025-06-17 20:02:15.384275+01	7	helloworld	1	[{"added": {}}]	7	3
4	2025-06-17 21:04:29.461392+01	9	1234	1	[{"added": {}}]	7	3
5	2025-06-18 23:15:56.697669+01	4	amin	2	[{"changed": {"fields": ["Password"]}}]	7	3
6	2025-06-18 23:17:07.982392+01	9	1234	3		7	3
7	2025-06-18 23:17:07.992263+01	7	helloworld	3		7	3
8	2025-06-18 23:17:07.993221+01	4	amin	3		7	3
9	2025-06-18 23:32:16.278496+01	10	ziyad	2	[{"changed": {"fields": ["Email verification token"]}}]	7	3
10	2025-06-18 23:37:42.42627+01	6	JIN	2	[{"changed": {"fields": ["Email verification token"]}}]	7	3
11	2025-06-18 23:40:39.653585+01	11	yahya	2	[{"changed": {"fields": ["Email verification token"]}}]	7	3
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	core	booking
7	core	user
8	core	partner
9	core	listing
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-06-04 10:43:06.323449+01
2	contenttypes	0002_remove_content_type_name	2025-06-04 10:59:09.349088+01
3	auth	0001_initial	2025-06-04 10:59:09.502964+01
4	auth	0002_alter_permission_name_max_length	2025-06-04 10:59:09.50701+01
5	auth	0003_alter_user_email_max_length	2025-06-04 10:59:09.510748+01
6	auth	0004_alter_user_username_opts	2025-06-04 10:59:09.514216+01
7	auth	0005_alter_user_last_login_null	2025-06-04 10:59:09.5179+01
8	auth	0006_require_contenttypes_0002	2025-06-04 10:59:09.519421+01
9	auth	0007_alter_validators_add_error_messages	2025-06-04 10:59:09.522916+01
10	auth	0008_alter_user_username_max_length	2025-06-04 10:59:09.526453+01
11	auth	0009_alter_user_last_name_max_length	2025-06-04 10:59:09.530268+01
12	auth	0010_alter_group_name_max_length	2025-06-04 10:59:09.551543+01
13	auth	0011_update_proxy_permissions	2025-06-04 10:59:09.555904+01
14	auth	0012_alter_user_first_name_max_length	2025-06-04 10:59:09.559803+01
19	core	0002_alter_user_phone_number	2025-06-04 10:59:09.681042+01
20	sessions	0001_initial	2025-06-04 10:59:09.696762+01
21	core	0003_alter_user_phone_number	2025-06-04 11:00:34.114555+01
22	core	0004_remove_booking_user_id_booking_user_user_created_at_and_more	2025-06-06 13:24:24.95708+01
23	core	0005_listing	2025-06-06 23:45:14.841277+01
24	core	0001_initial	2025-06-07 01:22:05.447929+01
25	admin	0001_initial	2025-06-07 01:22:05.484462+01
26	admin	0002_logentry_remove_auto_add	2025-06-07 01:22:05.49229+01
27	admin	0003_logentry_add_action_flag_choices	2025-06-07 01:22:05.49936+01
28	core	0002_user_email_verification_token	2025-06-09 01:36:24.506515+01
29	core	0003_alter_user_options_partner_verification_document_and_more	2025-06-17 08:18:35.936897+01
30	core	0004_user_email_verified	2025-06-17 08:19:18.989894+01
31	core	0005_remove_partner_verification_document_and_more	2025-06-17 08:33:36.324765+01
32	core	0006_partner_verification_document_user_email_verified	2025-06-17 08:33:46.878042+01
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: airbcar_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
22sarmev6ox8n0z70mms61ysvhuqijhi	.eJxVjDsOwjAQBe_iGlnxd21K-pzBWmdXOIBsKU4qxN2RpRTQvpl5b5Hw2Es6Om9pJXEVRlx-t4zLk-sA9MB6b3Jpdd_WLIciT9rl3Ihft9P9OyjYy6gZzYLKuagQSFtPlkl7nykEZS0jGq-DnygCYDBgGTgrRXFCAE1OfL7p-Tep:1uRQTq:VJe9hB9U2wX-gVEa2tzKFeouboaHME5DvpP0cGHHkx0	2025-07-01 08:11:38.683627+01
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: core_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.core_booking_id_seq', 1, true);


--
-- Name: core_listing_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.core_listing_id_seq', 2, true);


--
-- Name: core_partner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.core_partner_id_seq', 6, true);


--
-- Name: core_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.core_user_groups_id_seq', 1, false);


--
-- Name: core_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.core_user_id_seq', 11, true);


--
-- Name: core_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.core_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 11, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: airbcar_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: core_booking core_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_booking
    ADD CONSTRAINT core_booking_pkey PRIMARY KEY (id);


--
-- Name: core_listing core_listing_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_listing
    ADD CONSTRAINT core_listing_pkey PRIMARY KEY (id);


--
-- Name: core_partner core_partner_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_partner
    ADD CONSTRAINT core_partner_pkey PRIMARY KEY (id);


--
-- Name: core_partner core_partner_user_id_key; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_partner
    ADD CONSTRAINT core_partner_user_id_key UNIQUE (user_id);


--
-- Name: core_user_groups core_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_pkey PRIMARY KEY (id);


--
-- Name: core_user_groups core_user_groups_user_id_group_id_c82fcad1_uniq; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_user_id_group_id_c82fcad1_uniq UNIQUE (user_id, group_id);


--
-- Name: core_user core_user_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user
    ADD CONSTRAINT core_user_pkey PRIMARY KEY (id);


--
-- Name: core_user_user_permissions core_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: core_user_user_permissions core_user_user_permissions_user_id_permission_id_73ea0daa_uniq; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permissions_user_id_permission_id_73ea0daa_uniq UNIQUE (user_id, permission_id);


--
-- Name: core_user core_user_username_key; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user
    ADD CONSTRAINT core_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: core_booking_listing_id_582d4cc6; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_booking_listing_id_582d4cc6 ON public.core_booking USING btree (listing_id);


--
-- Name: core_booking_user_id_55d9bfa8; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_booking_user_id_55d9bfa8 ON public.core_booking USING btree (user_id);


--
-- Name: core_listing_partner_id_54f9cd4a; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_listing_partner_id_54f9cd4a ON public.core_listing USING btree (partner_id);


--
-- Name: core_partne_verific_d03d23_idx; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_partne_verific_d03d23_idx ON public.core_partner USING btree (verification_status);


--
-- Name: core_user_email_38052c_idx; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_user_email_38052c_idx ON public.core_user USING btree (email);


--
-- Name: core_user_groups_group_id_fe8c697f; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_user_groups_group_id_fe8c697f ON public.core_user_groups USING btree (group_id);


--
-- Name: core_user_groups_user_id_70b4d9b8; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_user_groups_user_id_70b4d9b8 ON public.core_user_groups USING btree (user_id);


--
-- Name: core_user_user_permissions_permission_id_35ccf601; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_user_user_permissions_permission_id_35ccf601 ON public.core_user_user_permissions USING btree (permission_id);


--
-- Name: core_user_user_permissions_user_id_085123d3; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_user_user_permissions_user_id_085123d3 ON public.core_user_user_permissions USING btree (user_id);


--
-- Name: core_user_username_36e4f7f7_like; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX core_user_username_36e4f7f7_like ON public.core_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: airbcar_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_booking core_booking_listing_id_582d4cc6_fk_core_listing_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_booking
    ADD CONSTRAINT core_booking_listing_id_582d4cc6_fk_core_listing_id FOREIGN KEY (listing_id) REFERENCES public.core_listing(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_booking core_booking_user_id_55d9bfa8_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_booking
    ADD CONSTRAINT core_booking_user_id_55d9bfa8_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_listing core_listing_partner_id_54f9cd4a_fk_core_partner_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_listing
    ADD CONSTRAINT core_listing_partner_id_54f9cd4a_fk_core_partner_id FOREIGN KEY (partner_id) REFERENCES public.core_partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_partner core_partner_user_id_a39e59f0_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_partner
    ADD CONSTRAINT core_partner_user_id_a39e59f0_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_groups core_user_groups_group_id_fe8c697f_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_group_id_fe8c697f_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_groups core_user_groups_user_id_70b4d9b8_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_user_id_70b4d9b8_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_user_permissions core_user_user_permi_permission_id_35ccf601_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permi_permission_id_35ccf601_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_user_permissions core_user_user_permissions_user_id_085123d3_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permissions_user_id_085123d3_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: airbcar_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

