# Generated by Django 4.2.21 on 2025-10-13 15:07

from django.db import migrations, connection

def fix_booking_listing_constraint(apps, schema_editor):
    # SQLite does NOT support DROP CONSTRAINT or ADD CONSTRAINT.
    # Skip the migration entirely when running on SQLite (e.g., CI).
    if connection.vendor == "sqlite":
        return

    # PostgreSQL-compatible SQL
    schema_editor.execute("""
    ALTER TABLE core_booking 
    DROP CONSTRAINT IF EXISTS core_booking_listing_id_582d4cc6_fk_core_listing_id;
    """)

    schema_editor.execute("""
    ALTER TABLE core_booking 
    ADD CONSTRAINT core_booking_listing_id_582d4cc6_fk_core_listing_id 
    FOREIGN KEY (listing_id) 
    REFERENCES core_listing(id) 
    ON DELETE CASCADE;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_partner_verification_status'),
    ]

    operations = [
        migrations.RunPython(fix_booking_listing_constraint),
    ]
